apiVersion: apps/v1
kind: Deployment
metadata:
  name: reseller-web-app-1-deployment
  namespace: reseller
  labels:
    app: reseller-web-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reseller-web-app-1
  template:
    metadata:
      labels:
        app: reseller-web-app-1
    spec:
      containers:
        - name: reseller-web-app-1
          image: apache-2:latest
          imagePullPolicy: Never   # force local image
          ports:
            - containerPort: 5000