apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-web-app-1-deployment
  namespace: erp
  labels:
    app: erp-web-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-web-app-1
  template:
    metadata:
      labels:
        app: erp-web-app-1
    spec:
      containers:
        - name: erp-web-app-1
          image: nginx-2:latest
          imagePullPolicy: Never   # force local image
          ports:
            - containerPort: 5000