apiVersion: apps/v1
kind: Deployment
metadata:
  name: reseller-api-1-deployment
  namespace: reseller
  labels:
    app: reseller-api-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reseller-api-1
  template:
    metadata:
      labels:
        app: reseller-api-1
    spec:
      containers:
        - name: reseller-api-1
          image: apache-1:latest
          imagePullPolicy: Never   # force local image
          ports:
            - containerPort: 5000