apiVersion: v1
kind: Service
metadata:
  name: reseller-api-1-service
  namespace: reseller
spec:
  type: NodePort
  selector:
    app: reseller-api-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007