apiVersion: v1
kind: Service
metadata:
  name: apache-1-service
spec:
  type: NodePort
  selector:
    app: nginx-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30009