apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-2-deployment
  namespace: apache
  labels:
    app: apache-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-2
  template:
    metadata:
      labels:
        app: apache-2
    spec:
      containers:
        - name: apache-2
          image: apache-2:latest
          imagePullPolicy: Never   # force local image
          ports:
            - containerPort: 5000