apiVersion: v1
kind: Service
metadata:
  name: apache-2-service
  namespace: apache
spec:
  type: NodePort
  selector:
    app: apache-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30008