apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-api-1-deployment
  namespace: erp
  labels:
    app: erp-api-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: erp-api-1
  template:
    metadata:
      labels:
        app: erp-api-1
    spec:
      containers:
        - name: erp-api-1
          image: nginx-1:latest
          imagePullPolicy: Never   # force local image
          ports:
            - containerPort: 5000