apiVersion: v1
kind: Service
metadata:
  name: erp-api-1-service
  namespace: erp
spec:
  type: NodePort
  selector:
    app: erp-api-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30009